export const users = [
  {
    email: 'Raymundo.Romaguera34@yahoo.com',
    roleId: 1,
    departmentId: 1,
    id: '1',
  },
  {
    email: 'Gabriella54@gmail.com',
    roleId: 2,
    departmentId: 1,
    id: '2',
  },
  {
    email: 'Demarcus_Mosciski@yahoo.com',
    roleId: 3,
    departmentId: 1,
    id: '3',
  },
  {
    email: 'Eulah.Bergnaum7@gmail.com',
    roleId: 1,
    departmentId: 2,
    id: '4',
  },
  {
    email: 'Maryse58@hotmail.com',
    roleId: 2,
    departmentId: 2,
    id: '5',
  },
  {
    email: 'Sylvester42@hotmail.com',
    roleId: 2,
    departmentId: 3,
    id: '6',
  },
  {
    email: 'Adrian_Rowe@yahoo.com',
    roleId: 3,
    departmentId: 3,
    id: '7',
  },
  {
    email: 'Stefanie.Cronin56@gmail.com',
    roleId: 1,
    departmentId: 3,
    id: '8',
  },
  {
    email: 'Eleazar_Keebler73@hotmail.com',
    roleId: 2,
    departmentId: 3,
    id: '9',
  },
  {
    email: 'Nina_Runolfsson@hotmail.com',
    roleId: 1,
    departmentId: 4,
    id: '10',
  },
  {
    email: 'Coleman.Schultz@yahoo.com',
    roleId: 3,
    departmentId: 4,
    id: '11',
  },
  {
    email: 'Damion.Bartoletti@hotmail.com',
    roleId: 1,
    departmentId: 5,
    id: '12',
  },
  {
    email: 'Patricia42@hotmail.com',
    roleId: 3,
    departmentId: 5,
    id: '13',
  },
  {
    email: 'Elvera32@gmail.com',
    roleId: 1,
    departmentId: 5,
    id: '14',
  },
  {
    email: 'test',
    roleId: 3,
    departmentId: 4,
    id: '15',
  },
  {
    email: 'test',
    roleId: 2,
    departmentId: 6,
    id: '17',
  },
  {
    email: 'test',
    roleId: 1,
    departmentId: 1,
    id: '18',
  },
  {
    email: 'aneta459520@gmail.com',
    roleId: 2,
    departmentId: 6,
    id: '19',
  },
  {
    email: 'aneta459520@gmail.com',
    roleId: 2,
    departmentId: 6,
    id: '20',
  },
  {
    email: 'aneta459520@gmail.com',
    roleId: 1,
    departmentId: 6,
    id: '21',
  },
  {
    email: 'aneta459520@gmail.com',
    roleId: 2,
    departmentId: 6,
    id: '25',
  },
  {
    email: 'test',
    roleId: 2,
    departmentId: 4,
    id: '26',
  },
  {
    email: 'aneta459520@gmail.com',
    roleId: 1,
    departmentId: 4,
    id: '27',
  },
  {
    email: 'Fay_Lynch53@yahoo.com',
    roleId: 1,
    departmentId: 3,
    id: '28',
  },
  {
    email: 'Amani.Medhurst@hotmail.com',
    roleId: 2,
    departmentId: 3,
    id: '29',
  },
  {
    email: 'Aurore66@yahoo.com',
    roleId: 1,
    departmentId: 2,
    id: '30',
  },
  {
    email: 'Kamille_Hauck@hotmail.com',
    roleId: 2,
    departmentId: 3,
    id: '31',
  },
  {
    email: 'Diamond.Gorczany22@hotmail.com',
    roleId: 3,
    departmentId: 4,
    id: '32',
  },
  {
    email: 'Geoffrey14@gmail.com',
    roleId: 1,
    departmentId: 4,
    id: '33',
  },
  {
    email: 'Elvera1@gmail.com',
    roleId: 1,
    departmentId: 3,
    id: '34',
  },
  {
    email: 'Syble_Hane0@gmail.com',
    roleId: 1,
    departmentId: 3,
    id: '35',
  },
  {
    email: 'Maxie_Vandervort5@yahoo.com',
    roleId: 1,
    departmentId: 6,
    id: '36',
  },
  {
    email: 'Pierce_Hamill@hotmail.com',
    roleId: 2,
    departmentId: 2,
    id: '37',
  },
  {
    email: 'Jazmyne.Rath@yahoo.com',
    roleId: 3,
    departmentId: 6,
    id: '38',
  },
  {
    email: 'Arthur_Klein@hotmail.com',
    roleId: 2,
    departmentId: 3,
    id: '39',
  },
  {
    email: 'Ruben57@yahoo.com',
    roleId: 2,
    departmentId: 2,
    id: '40',
  },
  {
    email: 'Juwan.Mertz@gmail.com',
    roleId: 1,
    departmentId: 5,
    id: '41',
  },
  {
    email: 'Amanda.Wintheiser25@hotmail.com',
    roleId: 1,
    departmentId: 3,
    id: '42',
  },
  {
    email: 'Ramona_Hackett@gmail.com',
    roleId: 1,
    departmentId: 5,
    id: '43',
  },
  {
    email: 'Thad.Turcotte@gmail.com',
    roleId: 1,
    departmentId: 4,
    id: '44',
  },
  {
    email: 'Cletus74@gmail.com',
    roleId: 1,
    departmentId: 2,
    id: '45',
  },
  {
    email: 'Adalberto_Russel@hotmail.com',
    roleId: 1,
    departmentId: 2,
    id: '46',
  },
  {
    email: 'Anabelle.Baumbach87@gmail.com',
    roleId: 2,
    departmentId: 2,
    id: '47',
  },
  {
    email: 'Bill_Rutherford@yahoo.com',
    roleId: 1,
    departmentId: 6,
    id: '48',
  },
  {
    email: 'Camron42@hotmail.com',
    roleId: 3,
    departmentId: 2,
    id: '49',
  },
  {
    email: 'Marcellus_Rempel2@yahoo.com',
    roleId: 2,
    departmentId: 2,
    id: '50',
  },
  {
    email: 'Velma.Kunze90@yahoo.com',
    roleId: 2,
    departmentId: 6,
    id: '51',
  },
  {
    email: 'Celine_Kuhn@yahoo.com',
    roleId: 1,
    departmentId: 1,
    id: '52',
  },
  {
    email: 'Dillan.Bergnaum@hotmail.com',
    roleId: 3,
    departmentId: 2,
    id: '53',
  },
  {
    email: 'Keon.Hintz@hotmail.com',
    roleId: 1,
    departmentId: 4,
    id: '54',
  },
  {
    email: 'ssd',
    roleId: '1',
    departmentId: 44,
    id: '55',
  },
  {
    email: 'ssd',
    roleId: '2',
    departmentId: 96,
    id: '56',
  },
  {
    email: 'asd',
    roleId: null,
    departmentId: 5,
    id: '57',
  },
  {
    email: 'sadasd',
    roleId: null,
    departmentId: 69,
    id: '58',
  },
  {
    email: 'sadasd',
    roleId: null,
    departmentId: 81,
    id: '59',
  },
  {
    email: 'sadasd',
    roleId: null,
    departmentId: 24,
    id: '60',
  },
  {
    email: 'fff',
    roleId: null,
    departmentId: 36,
    id: '61',
  },
  {
    email: 2,
    roleId: null,
    departmentId: 78,
    id: '62',
  },
  {
    email: 's',
    roleId: 2,
    departmentId: 5,
    id: '63',
  },
  {
    email: 'test@gmail.com',
    roleId: 2,
    departmentId: 44,
    id: '64',
  },
  {
    email: 'test@test.pl',
    roleId: 1,
    departmentId: 14,
    id: '65',
  },
  {
    email: 's',
    roleId: null,
    departmentId: 93,
    id: '66',
  },
  {
    email: 's',
    roleId: 3,
    departmentId: 22,
    id: '67',
  },
  {
    email: 's',
    roleId: 2,
    departmentId: 27,
    id: '68',
  },
  {
    email: 's',
    roleId: 1,
    departmentId: 66,
    id: '69',
  },
  {
    email: 'test@gmail.com',
    roleId: 2,
    departmentId: 46,
    id: '70',
  },
  {
    email: null,
    roleId: null,
    departmentId: 90,
    id: '71',
  },
  {
    email: 'damian@damian.pl',
    roleId: 'user',
    departmentId: 59,
    id: '72',
  },
];

const roles = [
  {
    id: 1,
    role: 'user',
  },
  {
    id: 2,
    role: 'admin',
  },
  {
    id: 3,
    role: 'super-admin',
  },
];

const jobPost = [
  {
    title: 'UX ',
    description: 'Corporate',
    jobTagIds: [1, 2, 11],
    id: '1',
  },
  {
    title: 'Senior Web Analyst',
    description: 'Product',
    jobTagIds: ['1'],
    id: '5',
  },
  {
    title: 'Forward Group Analyst',
    description: 'Investor',
    jobTagIds: ['2'],
    id: '6',
  },
  {
    title: 'Customer Paradigm Producer',
    description: 'Dynamic',
    jobTagIds: ['2'],
    id: '7',
  },
  {
    title: 'Customer Interactions Planner',
    description: 'Corporate',
    jobTagIds: ['2'],
    id: '9',
  },
  {
    title: 'Direct Operations Developer',
    description: 'Regional',
    jobTagIds: ['3'],
    id: '10',
  },
  {
    title: 'District Directives Liaison',
    description: 'District',
    jobTagIds: ['3'],
    id: '11',
  },
  {
    title: 'Customer Data Designer',
    description: 'Investor',
    jobTagIds: ['3'],
    id: '12',
  },
  {
    title: 'Investor Division Producer',
    description: 'Investor',
    jobTagIds: ['2'],
    id: '13',
  },
  {
    title: 'Forward Response Consultant',
    description: 'National',
    jobTagIds: ['3'],
    id: '14',
  },
  {
    title: 'Lead Program Consultant',
    description: 'Lead',
    jobTagIds: ['3'],
    id: '15',
  },
  {
    title: 'Senior Infrastructure Consultant',
    description: 'Direct',
    jobTagIds: ['3'],
    id: '17',
  },
  {
    title: 'International Program Architect',
    description: 'National',
    jobTagIds: ['3'],
    id: '18',
  },
  {
    title: 'Investor Usability Orchestrator',
    description: 'Dynamic',
    jobTagIds: ['4'],
    id: '19',
  },
  {
    title: 'Legacy Directives Associate',
    description: 'Direct',
    jobTagIds: [],
    id: '20',
  },
  {
    title: 'Principal Tactics Manager',
    description: 'International',
    jobTagIds: [],
    id: '21',
  },
  {
    title: 'Dynamic Identity Administrator',
    description: 'International',
    jobTagIds: [],
    id: '22',
  },
  {
    title: 'Corporate Brand Architect',
    description: 'Direct',
    jobTagIds: [],
    id: '23',
  },
  {
    title: 'Investor Mobility Liaison',
    description: 'Product',
    jobTagIds: [],
    id: '24',
  },
  {
    title: 'National Functionality Technician',
    description: 'District',
    jobTagIds: [],
    id: '25',
  },
  {
    title: 'Chief Infrastructure Supervisor',
    description: 'Central',
    jobTagIds: [],
    id: '26',
  },
  {
    title: 'International Communications Specialist',
    description: 'Forward',
    jobTagIds: [],
    id: '27',
  },
  {
    title: 'Internal Mobility Coordinator',
    description: 'Central',
    jobTagIds: [],
    id: '28',
  },
  {
    title: 'Legacy Implementation Coordinator',
    description: 'Internal',
    jobTagIds: [],
    id: '29',
  },
  {
    title: 'Internal Intranet Facilitator',
    description: 'Direct',
    jobTagIds: [],
    id: '30',
  },
  {
    title: 'Corporate Interactions Facilitator',
    description: 'National',
    jobTagIds: [],
    id: '31',
  },
  {
    title: 'Legacy Accounts Architect',
    description: 'International',
    jobTagIds: [],
    id: '32',
  },
  {
    title: 'Lead Configuration Liaison',
    description: 'International',
    jobTagIds: [],
    id: '33',
  },
  {
    title: 'National Tactics Planner',
    description: 'International',
    jobTagIds: [],
    id: '34',
  },
  {
    title: 'International Marketing Consultant',
    description: 'Corporate',
    jobTagIds: [],
    id: '35',
  },
  {
    title: 'Internal Creative Producer',
    description: 'Dynamic',
    jobTagIds: [],
    id: '36',
  },
  {
    title: 'District Accountability Officer',
    description: 'Senior',
    jobTagIds: [],
    id: '37',
  },
  {
    title: 'Future Applications Engineer',
    description: 'Human',
    jobTagIds: [],
    id: '38',
  },
  {
    title: 'International Research Orchestrator',
    description: 'Central',
    jobTagIds: [],
    id: '39',
  },
  {
    title: 'Global Metrics Planner',
    description: 'Forward',
    jobTagIds: [],
    id: '40',
  },
  {
    title: 'Central Communications Assistant',
    description: 'International',
    jobTagIds: [],
    id: '41',
  },
  {
    title: 'National Creative Representative',
    description: 'National',
    jobTagIds: [],
    id: '42',
  },
  {
    title: 'Product Applications Producer',
    description: 'Principal',
    jobTagIds: [],
    id: '43',
  },
  {
    title: 'Forward Creative Representative',
    description: 'Chief',
    jobTagIds: [],
    id: '44',
  },
  {
    title: 'Chief Accounts Planner',
    description: 'International',
    jobTagIds: [],
    id: '45',
  },
  {
    title: 'Customer Tactics Planner',
    description: 'Forward',
    jobTagIds: [],
    id: '47',
  },
  {
    title: 'Global Response Facilitator',
    description: 'Central',
    jobTagIds: [],
    id: '48',
  },
  {
    title: 'Internal Metrics Administrator',
    description: 'Global',
    jobTagIds: [],
    id: '49',
  },
  {
    title: 'Forward Branding Designer',
    description: 'Investor',
    jobTagIds: [],
    id: '50',
  },
  {
    title: 'Direct Optimization Supervisor',
    description: 'Lead',
    jobTagIds: [],
    id: '51',
  },
  {
    title: 'Direct Division Engineer',
    description: 'Lead',
    jobTagIds: [],
    id: '52',
  },
  {
    title: 'Forward Integration Facilitator',
    description: 'Customer',
    jobTagIds: [],
    id: '53',
  },
  {
    title: 'Global Quality Representative',
    description: 'Lead',
    jobTagIds: [],
    id: '54',
  },
  {
    title: 'National Integration Developer',
    description: 'District',
    jobTagIds: [],
    id: '55',
  },
  {
    title: 'Principal Creative Associate',
    description: 'Corporate',
    jobTagIds: [],
    id: '56',
  },
  {
    title: 'National Applications Officer',
    description: 'Chief',
    jobTagIds: [],
    id: '57',
  },
  {
    title: 'Dynamic Usability Administrator',
    description: 'Global',
    jobTagIds: [],
    id: '58',
  },
  {
    title: 'Direct Accounts Architect',
    description: 'Product',
    jobTagIds: [],
    id: '59',
  },
  {
    title: 'Central Applications Developer',
    description: 'Forward',
    jobTagIds: [],
    id: '60',
  },
  {
    title: 'Future Accounts Manager',
    description: 'Internal',
    jobTagIds: [],
    id: '61',
  },
  {
    title: 'International Applications Supervisor',
    description: 'Human',
    jobTagIds: [],
    id: '62',
  },
  {
    title: 'Customer Branding Developer',
    description: 'Customer',
    jobTagIds: [],
    id: '63',
  },
  {
    title: 'Corporate Mobility Orchestrator',
    description: 'Customer',
    jobTagIds: [],
    id: '64',
  },
  {
    title: 'Future Optimization Representative',
    description: 'Forward',
    jobTagIds: [],
    id: '65',
  },
  {
    title: 'District Metrics Strategist',
    description: 'National',
    jobTagIds: [],
    id: '66',
  },
  {
    title: 'Legacy Implementation Architect',
    description: 'Senior',
    jobTagIds: [],
    id: '67',
  },
  {
    title: 'Global Accounts Administrator',
    description: 'Future',
    jobTagIds: [],
    id: '68',
  },
  {
    title: 'Future Division Representative',
    description: 'Human',
    jobTagIds: [],
    id: '69',
  },
  {
    title: 'Human Functionality Representative',
    description: 'Direct',
    jobTagIds: [],
    id: '70',
  },
  {
    title: 'International Identity Orchestrator',
    description: 'Senior',
    jobTagIds: [],
    id: '71',
  },
  {
    title: 'International Assurance Liaison',
    description: 'Forward',
    jobTagIds: [],
    id: '72',
  },
  {
    title: 'Principal Intranet Agent',
    description: 'Chief',
    jobTagIds: [],
    id: '73',
  },
  {
    title: 'Senior Accountability Agent',
    description: 'Internal',
    jobTagIds: [],
    id: '74',
  },
  {
    title: 'Lead Quality Technician',
    description: 'Chief',
    jobTagIds: [],
    id: '75',
  },
  {
    title: 'Direct Directives Architect',
    description: 'Human',
    jobTagIds: [],
    id: '76',
  },
  {
    title: 'Principal Intranet Director',
    description: 'District',
    jobTagIds: [],
    id: '77',
  },
  {
    title: 'Regional Optimization Coordinator',
    description: 'Customer',
    jobTagIds: [],
    id: '78',
  },
  {
    title: 'Product Marketing Assistant',
    description: 'Legacy',
    jobTagIds: [],
    id: '79',
  },
  {
    title: 'Human Creative Coordinator',
    description: 'Direct',
    jobTagIds: [],
    id: '80',
  },
  {
    title: 'Corporate Directives Developer',
    description: 'Forward',
    jobTagIds: [],
    id: '81',
  },
  {
    title: 'Dynamic Configuration Consultant',
    description: 'District',
    jobTagIds: [],
    id: '82',
  },
  {
    title: 'Customer Optimization Planner',
    description: 'Future',
    jobTagIds: [],
    id: '83',
  },
  {
    title: 'Lead Division Orchestrator',
    description: 'Dynamic',
    jobTagIds: [],
    id: '84',
  },
  {
    title: 'Principal Marketing Developer',
    description: 'International',
    jobTagIds: [],
    id: '85',
  },
  {
    title: 'Senior Infrastructure Strategist',
    description: 'Customer',
    jobTagIds: [],
    id: '86',
  },
  {
    title: 'District Web Producer',
    description: 'Dynamic',
    jobTagIds: [],
    id: '87',
  },
  {
    title: 'District Markets Designer',
    description: 'Direct',
    jobTagIds: [],
    id: '88',
  },
  {
    title: 'District Quality Facilitator',
    description: 'Direct',
    jobTagIds: [],
    id: '89',
  },
  {
    title: 'Central Brand Architect',
    description: 'Corporate',
    jobTagIds: [],
    id: '90',
  },
  {
    title: 'Investor Usability Manager',
    description: 'Direct',
    jobTagIds: [],
    id: '91',
  },
  {
    title: 'Senior Metrics Developer',
    description: 'Lead',
    jobTagIds: [],
    id: '92',
  },
  {
    title: 'Legacy Functionality Associate',
    description: 'Lead',
    jobTagIds: [],
    id: '93',
  },
  {
    title: 'Human Metrics Orchestrator',
    description: 'Forward',
    jobTagIds: [],
    id: '95',
  },
  {
    title: 'Investor Markets Analyst',
    description: 'Forward',
    jobTagIds: [],
    id: '96',
  },
  {
    title: 'Principal Identity Administrator',
    description: 'Dynamic',
    jobTagIds: [],
    id: '97',
  },
  {
    title: 'Frontend',
    description: 'Awesome',
    jobTagIds: [5, 1, 7],
    id: '99',
  },
  {
    title: 'Lead Division Engineer',
    description: 'National',
    jobTagIds: [],
    id: '100',
  },
  {
    title: 'Principal Data Associate',
    description: 'Forward',
    jobTagIds: [],
    id: '101',
  },
  {
    title: 'National Group Administrator',
    description: 'Lead',
    jobTagIds: [],
    id: '102',
  },
  {
    title: 'Senior Usability Technician',
    description: 'Investor',
    jobTagIds: [],
    id: '103',
  },
  {
    title: 'Regional Group Planner',
    description: 'Dynamic',
    jobTagIds: [],
    id: '104',
  },
  {
    title: 'Chief Directives Executive',
    description: 'National',
    jobTagIds: [],
    id: '105',
  },
  {
    title: 'Regional Brand Executive',
    description: 'Dynamic',
    jobTagIds: [],
    id: '106',
  },
  {
    title: 'Global Intranet Engineer',
    description: 'Senior',
    jobTagIds: [],
    id: '107',
  },
  {
    title: 'Senior Mobility Engineer',
    description: 'Senior',
    jobTagIds: [],
    id: '108',
  },
];

const jobTags = [
  {
    name: 'IT',
    id: '1',
  },
  {
    name: 'DevOps',
    id: '2',
    title: 'Legacy Functionality Strategist',
    description: 'Seniorsdf',
    jobTagIds: [1, 3, 6],
  },
  {
    name: 'Testing',
    id: '3',
  },
  {
    name: 'Backend',
    id: '4',
  },
  {
    name: 'Frontend',
    id: '5',
  },
  {
    name: 'Analytics',
    id: '6',
  },
  {
    name: 'UX/UI',
    id: '7',
  },
  {
    name: 'Test',
    id: '8',
  },
  {
    name: 'Testing',
    id: '9',
  },
  {
    name: 'Hi-end Backend ',
    id: '10',
  },
  {
    name: 'Testing33',
    id: '11',
  },
  {
    name: 'Testing333',
    id: '12',
  },
  {
    name: 'test',
    id: '13',
  },
  {
    name: 'test',
    id: '14',
  },
];

const departments = [
  {
    name: 'Development',
    id: '1',
  },
  {
    name: 'Management',
    id: '2',
  },
  {
    name: 'Product',
    id: '3',
  },
  {
    name: 'Design',
    id: '4',
  },
  {
    name: 'Marketing',
    id: '5',
  },
  {
    name: 'Sales',
    id: '6',
  },
];

const products = [
  {
    name: 'Product 1',
    price: 45,
    colorId: '1',
    storeId: '1',
    id: '1',
  },
  {
    name: 'Product 2',
    price: 8,
    colorId: '2',
    storeId: '2',
    id: '2',
  },
  {
    name: 'Product 3',
    price: 61,
    colorId: '3',
    storeId: '3',
    id: '3',
  },
  {
    name: 'Product 4',
    price: 120,
    colorId: '4',
    storeId: '4',
    id: '4',
  },
  {
    name: 'Product 5',
    price: 124,
    colorId: '1',
    storeId: '1',
    id: '5',
  },
  {
    name: 'Product 6',
    price: 34,
    colorId: '2',
    storeId: '1',
    id: '6',
  },
  {
    name: 'Product 7',
    price: 1,
    colorId: '3',
    storeId: '2',
    id: '7',
  },
  {
    name: 'Product 8',
    price: 61,
    colorId: '1',
    storeId: '2',
    id: '8',
  },
  {
    name: 'Product 9',
    price: 7,
    colorId: '2',
    storeId: '4',
    id: '9',
  },
];
